### ISSUE TITLE
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/react-components-as-routes#10]
This lesson had a dependency that used require-from-string, an NPM package published by floatdrop, who recently deleted his NPM account, taking all his NPM packages with it. Currently, there is a work around by directly installing the package from his github using the following command in the lesson root directory:

`npm install https://github.com/floatdrop/require-from-string/tarball/v1.1.0 --save`
`npm install`

**Comment by DanielSeehausen** [comment]
Hi there @f3mshep ,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local vs IDE, npm + node version, etc.), I'd be happy to take a second look!

As always, thanks for contributing! 💙
