### ISSUE TITLE
navlinks section was removed

### ISSUE THREAD

**Issue by DanielSeehausen** [learn-co-curriculum/react-components-as-routes#15]
in previous version before most recent overhaul. move into part 2

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @DanielSeehausen .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by DanielSeehausen** [comment]
Savage with that auto response max
