### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-components-as-routes#17]
First the lesson says to do this:
"In anticipation of a growing codebase, let's refactor by removing the components we defined in index.js and placing them in their own files in src/."

Then we are given instructions that assume that you did NOT do the above:
"Let's work on adding in the <NavLink> component to our application. For ease of display, we will work as if we still have all of our components in one file. If you have broken them out into individual component files, update accordingly:"

I commented out the files I just created, but that part seems like an unnecessary detour.

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for spotting this and providing feedback. We've updated this lessons readme, moving the refactor portion to the end of the lesson and updated the code snippets so the lesson flows more sensically.

Thank you for contributing!
