### ISSUE TITLE
No console error thrown where error expected as per code along directions

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/react-components-as-routes#18]
No error thrown, app compiles correctly and does not throw any console errors as expected by code along instructions:

"Following, let's add our /about and /login routes to our router:

    // ./src/index.js
     
    ReactDOM.render((
      <Router>
          <Route path="/" render={Home} />
          <Route exact path="/about" render={About} />
          <Route exact path="/login" render={Login} />
      </Router>),
      document.getElementById('root')
    );

Reload your browser and look at our beautiful routes...oops! Error:

A <Router> may have only one child element"

**Comment by gac2117** [comment]
That's strange. For me, it does give me an error if I don't add `<React.Fragment>` inside `<Router>`. But what I don't understand is why we can't use `<>` and `</>`.

**Comment by maxwellbenton** [comment]
Hi @atxrenegade,

Thank you for spotting this and providing feedback. There is some strange behavior here regarding fragments. To avoid unexpected behavior, we've updated this lesson to use a `div`. We apologize for any confusion this may have caused, but thank you for letting us know about this issue!
