### ISSUE TITLE
No test to be run

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/react-components-as-routes#2]
@aturkewi @Lukeghenco 

Can't get the green light due to no test in the code along! Sad day!

**Comment by aturkewi** [comment]
Toggled it to a readme. 
All set!

**Comment by crwhitesides** [comment]
@aturkewi this lesson is still showing up as a lab on my end. I'm unable to get the 'green light' because there are no tests to run. 😭

**Comment by Lukeghenco** [comment]
@crwhitesides just redeployed this and set it to readme this morning. Everything is good to go. Thanks.
