### ISSUE TITLE
Erroneous and Error-producing Code Block in Example

### ISSUE THREAD

**Issue by d-otis** [learn-co-curriculum/react-components-as-routes#37]
In the introduction of `NavLinks`, within the first illustrative code example that defines and assigns `const Navbar` all of the `<NavLink/>`s as a whole should be wrapped in a `return` statement. (line 17)

The other examples further along in this lesson however appear to be correct.

**Comment by ihollander** [comment]
Fixed by https://github.com/learn-co-curriculum/react-components-as-routes/commit/c5a686ebf9cd57d373329705cacdd68ad435ce04
