### ISSUE TITLE
some confusing things about this walkthrough

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/react-components-as-routes#4]
There's a couple of things that seem to be a little out of order/need tweaking.

There's this code snipet that is explained afterwards:

```
// .src/index.js
 
import React from 'react';
import ReactDOM from 'react-dom';
// Step 1. Import react-router functions
import { BrowserRouter as Router, Route } from 'react-router-dom';
 
const App = () => {
  return (
    <div>
      <h1>Home</h1>
    </div>
  );
};
 
// Step 2. Changed to have router coordinate what is displayed
ReactDOM.render((
  <Router>
    <Route path="/" component={App} />
  </Router>), 
  document.getElementById('root')
);
The description then goes on to say:
```

`We are using the render prop in the Route component, but we could have used component={Home} instead. With render we are just invoking a function call to render <div><h1>Home</h1></div>.`

The issue is when you talk about using the render prop in the Route component.

Then he next code snipet is:

```
// ./src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router, Route } from 'react-router-dom';
 
const App = () => {
  return (
    <div>
      <Router>
        <Route exact path="/" render={() => <h1>Home</h1>} />
      </Router>
    </div>
  );
};
 
ReactDOM.render(
  <App />, 
  document.getElementById('root')
);
```

It seems to me that this code snipet is the one the first one should be. ?

Also later on in the walkthrough there's this:

```
NAVLINKS
What good are routes, if users don't know how to find them or what they are?
The React Router API comes with two options of adding in Links: and . The both have the same base level functionality...
```

This seems unclear as to what the two options for adding links are.

@briOD originally posted here: https://github.com/learn-co-students/react-components-as-routes-v-000/issues/12#issuecomment-308567520

@Lukeghenco is this something you might be able to take a look at?

**Comment by gb23** [comment]
I would HIGHLY recommend implementing the fixes mentioned above.  This lesson, at times, is shuffled out of sequence.

**Comment by aturkewi** [comment]
@curiositypaths tagging you in here :)

**Comment by dkStephanos** [comment]
This should really be done. The formatting of this read me is confusing and inaccurate

**Comment by DanielSeehausen** [comment]
will get on it today

**Comment by DanielSeehausen** [comment]
wip- branch has proposed changes to the lab. Currently it is a rough draft but it has done a lot to re-order the way things are taught, address that this issue brings to light, and add consistency. 

Proposal: everything re: navlinks and below should be a 'part II' code along. The length was getting away from us, and they are logically separable concepts. The navlinks portion is cut out of the proposed wip- branch. 

Please let me know if you have any input before I polish, merge, and close issue: @aturkewi , @dkStephanos , @gb23 , @curiositypaths , @Lukeghenco

**Comment by DanielSeehausen** [comment]
resolved @aturkewi , @dkStephanos , @gb23 , @curiositypaths , @Lukeghenco
